### ISSUE TITLE
can we find and blur area with nudity?

### ISSUE THREAD

**Issue by vinnitu** [mdietrichstein/tensorflow-open_nsfw#10]
can we find and blur area with nudity?

**Comment by mdietrichstein** [comment]
Sadly not with this project. tensorflow-open_nsfw only lets you classify images. There's no localization involved.

You would be better off with an object detector like yolo, mobile-ssd, etc. I'm not sure if there are pre-trained nsfw object detectors out there though. You might have to train one by yourself.
