### ISSUE TITLE
dataset production

### ISSUE THREAD

**Issue by yunhai0920** [mdietrichstein/tensorflow-open_nsfw#12]
hi,I am sorry to bother you, but i want to kown how do you make a data set? nsfw set maybe easy to classify,but the types of sfw images are too complex and huge, you can't include all the categories of sfw image.

**Comment by mdietrichstein** [comment]
Hi @yunhai0920,

I have not created the dataset by myself. I have used the pre-computed weights from Yahoo's OpenNsfw Project ([here](https://github.com/yahoo/open_nsfw)).

You can read more about their approach [here](https://yahooeng.tumblr.com/post/151148689421/open-sourcing-a-deep-learning-solution-for)
