### ISSUE TITLE
feed a batch of opencv images

### ISSUE THREAD

**Issue by r-y-zadeh** [mdietrichstein/tensorflow-open_nsfw#6]
I'll try to read a number of images with opencv and feed the batch of them to the model. but with both yahoo_loader and tensorflow_loader I got errors. is there a way to use opencv images instead of the tensorflow/yahoo loader?

**Comment by mdietrichstein** [comment]
I might add an OpenCV image loader in the future, but currently you would have to create your own. Take a look at the [yahoo loader implementation](https://github.com/mdietrichstein/tensorflow-open_nsfw/blob/cb56b1592ccbac901e22d06e26b8d3a74d0b45a0/image_utils.py#L4) for inspiration.
